{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 29,
   "id": "55814bd0-6fe2-4b59-af5c-c53fccd79c89",
   "metadata": {},
   "outputs": [],
   "source": [
    "import tkinter as tk\n",
    "from tkinter import messagebox\n",
    "from PIL import Image, ImageTk\n",
    "import random\n",
    "\n",
    "# Card and Deck classes\n",
    "suits = ('Hearts', 'Diamonds', 'Spades', 'Clubs')\n",
    "ranks = ('Two', 'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight', 'Nine', 'Ten', 'Jack', 'Queen', 'King', 'Ace')\n",
    "values = {'Two': 2, 'Three': 3, 'Four': 4, 'Five': 5, 'Six': 6, 'Seven': 7, 'Eight': 8, 'Nine': 9, 'Ten': 10,\n",
    "          'Jack': 10, 'Queen': 10, 'King': 10, 'Ace': 11}\n",
    "\n",
    "class Card:\n",
    "    def __init__(self, suit, rank):\n",
    "        self.suit = suit\n",
    "        self.rank = rank\n",
    "        self.value = values[rank]\n",
    "        self.image = ImageTk.PhotoImage(Image.open(f\"images/{rank}_of_{suit}.png\").resize((80, 120)))\n",
    "\n",
    "    def __str__(self):\n",
    "        return f\"{self.rank} of {self.suit} ({self.value})\"\n",
    "\n",
    "class Deck:\n",
    "    def __init__(self):\n",
    "        self.all_cards = [Card(suit, rank) for suit in suits for rank in ranks]\n",
    "\n",
    "    def shuffle(self):\n",
    "        random.shuffle(self.all_cards)\n",
    "\n",
    "    def deal_one(self):\n",
    "        return self.all_cards.pop()\n",
    "\n",
    "class Hand:\n",
    "    def __init__(self):\n",
    "        self.cards = []\n",
    "        self.value = 0\n",
    "        self.aces = 0\n",
    "\n",
    "    def add_card(self, card):\n",
    "        self.cards.append(card)\n",
    "        self.value += card.value\n",
    "        if card.rank == 'Ace':\n",
    "            self.aces += 1\n",
    "        self.adjust_for_ace()\n",
    "\n",
    "    def adjust_for_ace(self):\n",
    "        while self.value > 21 and self.aces:\n",
    "            self.value -= 10\n",
    "            self.aces -= 1\n",
    "\n",
    "    def __str__(self):\n",
    "        return ', '.join(str(card) for card in self.cards)\n",
    "\n",
    "class Chips:\n",
    "    def __init__(self, total=100):\n",
    "        self.total = total\n",
    "        self.bet = 0\n",
    "\n",
    "    def win_bet(self):\n",
    "        self.total += self.bet\n",
    "\n",
    "    def lose_bet(self):\n",
    "        self.total -= self.bet\n",
    "\n",
    "class BlackjackGame:\n",
    "    def __init__(self, root):\n",
    "        self.root = root\n",
    "        self.root.title(\"Blackjack\")\n",
    "        self.root.state('zoomed')  # Start in maximized mode (not fullscreen)\n",
    "        self.root.configure(bg=\"green\")\n",
    "\n",
    "        self.deck = Deck()\n",
    "        self.deck.shuffle()\n",
    "        self.player_hand = Hand()\n",
    "        self.dealer_hand = Hand()\n",
    "        self.chips = Chips()\n",
    "        self.player_turn = True\n",
    "\n",
    "        # Main frame (always visible, even in restore down mode)\n",
    "        self.main_frame = tk.Frame(root, bg=\"dark green\")\n",
    "        self.main_frame.pack(fill=tk.BOTH, expand=True)\n",
    "\n",
    "        # Left frame (fixed width for controls)\n",
    "        self.left_frame = tk.Frame(self.main_frame, bg=\"dark green\", width=300)\n",
    "        self.left_frame.grid(row=0, column=0, sticky=\"ns\", padx=10, pady=10)\n",
    "\n",
    "        # Right frame (expands for labels & canvases)\n",
    "        self.right_frame = tk.Frame(self.main_frame, bg=\"dark green\")\n",
    "        self.right_frame.grid(row=0, column=1, sticky=\"nsew\", padx=10, pady=10)\n",
    "\n",
    "        self.main_frame.grid_columnconfigure(1, weight=1)  # Right frame expands\n",
    "        self.main_frame.grid_rowconfigure(0, weight=1)  # Allow expansion\n",
    "\n",
    "        self.rules_window = None  # To track if the Rules window is open\n",
    "\n",
    "        # Rules Button (Top Right Corner)\n",
    "        self.rules_button = tk.Button(root, text=\"Rules\", font=(\"Helvetica\", 12, \"bold\"),\n",
    "                                      width=10, bg=\"#FFD700\", fg=\"black\",\n",
    "                                      command=self.show_rules)\n",
    "        self.rules_button.place(relx=1, x=-10, y=10, anchor=\"ne\")  # Top-right positioning\n",
    "\n",
    "        \n",
    "\n",
    "        # Labels (Player's and Dealer's text is centered above the canvas)\n",
    "        self.player_label = tk.Label(self.right_frame, text=\"Player's Hand: []\", font=(\"Helvetica\", 14), bg=\"dark green\", fg=\"white\")\n",
    "        self.player_label.pack(anchor=tk.CENTER, pady=5)\n",
    "\n",
    "        self.dealer_label = tk.Label(self.right_frame, text=\"Dealer's Hand: []\", font=(\"Helvetica\", 14), bg=\"dark green\", fg=\"white\")\n",
    "        self.dealer_label.pack(anchor=tk.CENTER, pady=5)\n",
    "\n",
    "        self.score_label = tk.Label(self.left_frame, text=\"Chips: 100\", font=(\"Helvetica\", 14), bg=\"dark green\", fg=\"white\")\n",
    "        self.score_label.grid(row=2, column=0, sticky=\"w\", pady=5)\n",
    "\n",
    "        # Bet entry\n",
    "        self.bet_label = tk.Label(self.left_frame, text=\"Enter your bet:\", font=(\"Helvetica\", 12), bg=\"dark green\", fg=\"white\")\n",
    "        self.bet_label.grid(row=3, column=0, sticky=\"w\", pady=5)\n",
    "\n",
    "        self.bet_entry = tk.Entry(self.left_frame, width=10)\n",
    "        self.bet_entry.grid(row=4, column=0, sticky=\"w\", pady=5)\n",
    "\n",
    "        # Control buttons in the left frame\n",
    "        button_style = {\n",
    "            \"font\": (\"Helvetica\", 12),\n",
    "            \"width\": 15,\n",
    "            \"bg\": \"#555555\",\n",
    "            \"fg\": \"white\",\n",
    "            \"activebackground\": \"#777777\",\n",
    "            \"activeforeground\": \"white\",\n",
    "            \"relief\": \"raised\",\n",
    "            \"borderwidth\": 3\n",
    "        }\n",
    "\n",
    "        self.bet_button = tk.Button(self.left_frame, text=\"Place Bet\", command=self.place_bet, **button_style)\n",
    "        self.bet_button.grid(row=5, column=0, pady=5, sticky=\"w\")\n",
    "\n",
    "        self.hit_button = tk.Button(self.left_frame, text=\"Hit\", command=self.hit, state=tk.DISABLED, **button_style)\n",
    "        self.hit_button.grid(row=6, column=0, pady=5, sticky=\"w\")\n",
    "\n",
    "        self.stand_button = tk.Button(self.left_frame, text=\"Stand\", command=self.stand, state=tk.DISABLED, **button_style)\n",
    "        self.stand_button.grid(row=7, column=0, pady=5, sticky=\"w\")\n",
    "\n",
    "        self.restart_button = tk.Button(self.left_frame, text=\"Restart\", command=self.restart_game, **button_style)\n",
    "        self.restart_button.grid(row=8, column=0, pady=5, sticky=\"w\")\n",
    "\n",
    "        self.next_round_button = tk.Button(self.left_frame, text=\"Next Round\", command=self.next_round, state=tk.DISABLED, **button_style)\n",
    "        self.next_round_button.grid(row=9, column=0, pady=5, sticky=\"w\")\n",
    "\n",
    "\n",
    "        # Canvas frame (only shows in maximized mode)\n",
    "        self.canvas_frame = tk.Frame(self.right_frame, bg=\"dark green\")\n",
    "\n",
    "        self.player_canvas = tk.Canvas(self.canvas_frame, width=800, height=300, bg=\"green\")\n",
    "        self.player_canvas.pack(side=tk.TOP, fill=tk.BOTH, expand=True, padx=5, pady=5)\n",
    "\n",
    "        self.dealer_canvas = tk.Canvas(self.canvas_frame, width=800, height=300, bg=\"green\")\n",
    "        self.dealer_canvas.pack(side=tk.BOTTOM, fill=tk.BOTH, expand=True, padx=5, pady=5)\n",
    "\n",
    "        # Back of card image\n",
    "        self.back_of_card_image = ImageTk.PhotoImage(Image.open(\"images/Back_of_Card.png\").resize((80, 120)))\n",
    "\n",
    "        # Bind window resize events\n",
    "        self.root.bind('<Configure>', self.check_window_state)\n",
    "\n",
    "    def check_window_state(self, event=None):\n",
    "        \"\"\"Ensure canvas only shows in maximized mode.\"\"\"\n",
    "        if self.root.state() == 'zoomed':  # Only show canvas in maximized mode\n",
    "            self.canvas_frame.pack(fill=tk.BOTH, expand=True)\n",
    "        else:\n",
    "            self.canvas_frame.pack_forget()  # Hide when restored down\n",
    "\n",
    "    def show_rules(self):\n",
    "        \"\"\"Display a single-instance pop-up window with Blackjack rules.\"\"\"\n",
    "        if self.rules_window and self.rules_window.winfo_exists():\n",
    "            # If window already exists, bring it to the front\n",
    "            self.rules_window.lift()\n",
    "            return\n",
    "\n",
    "        self.rules_window = tk.Toplevel(self.root)\n",
    "        self.rules_window.title(\"Blackjack Rules\")\n",
    "        self.rules_window.geometry(\"500x400\")\n",
    "        self.rules_window.configure(bg=\"white\")\n",
    "\n",
    "        # Scrollable Text Area\n",
    "        text_frame = tk.Frame(self.rules_window, bg=\"white\", padx=10, pady=10)\n",
    "        text_frame.pack(fill=tk.BOTH, expand=True)\n",
    "\n",
    "        rules_text = \"\"\"\\\n",
    "Blackjack Rules\n",
    "\n",
    "Objective:\n",
    "- Beat the dealer by having a hand value closer to 21 without exceeding it.\n",
    "\n",
    "Card Values:\n",
    "- Cards 2 to 10 are worth their face value.\n",
    "- Jacks, Queens, and Kings are worth 10 points each.\n",
    "- Aces are worth either 1 or 11 points, depending on what is more beneficial for the hand.\n",
    "\n",
    "Game Flow:\n",
    "1. Place your bet.\n",
    "2. Both you and the dealer receive two cards.\n",
    "   - One of the dealer's cards is hidden.\n",
    "3. Choose your action:\n",
    "   - Hit: Take another card to improve your total hand value.\n",
    "   - Stand: Keep your current hand as it is.\n",
    "4. Dealer's Turn:\n",
    "   - The dealer must hit if their hand is below 17.\n",
    "   - The dealer must stand if their hand is 17 or higher.\n",
    "\n",
    "Winning Conditions:\n",
    "- You win if your hand is higher than the dealer's without exceeding 21.\n",
    "- A hand consisting of an Ace and a 10-point card (a Blackjack) is an automatic win.\n",
    "- If your total exceeds 21, you lose (this is called a bust).\n",
    "- If you and the dealer have the same total, the round is a tie (push).\n",
    "\n",
    "💰 Good luck and enjoy the game! 🎲\n",
    "\"\"\"\n",
    "\n",
    "        # Scrollable text widget\n",
    "        text_widget = tk.Text(text_frame, wrap=\"word\", font=(\"Helvetica\", 12), bg=\"white\", padx=5, pady=5)\n",
    "        text_widget.insert(tk.END, rules_text)\n",
    "        text_widget.config(state=tk.DISABLED)  # Make it read-only\n",
    "        text_widget.pack(side=tk.LEFT, fill=tk.BOTH, expand=True)\n",
    "\n",
    "        # Add scrollbar\n",
    "        scrollbar = tk.Scrollbar(text_frame, command=text_widget.yview)\n",
    "        scrollbar.pack(side=tk.RIGHT, fill=tk.Y)\n",
    "        text_widget.config(yscrollcommand=scrollbar.set)\n",
    "\n",
    "    def place_bet(self):\n",
    "        try:\n",
    "            bet = int(self.bet_entry.get())\n",
    "            if bet <= 0 or bet > self.chips.total:\n",
    "                raise ValueError(\"Invalid bet amount.\")\n",
    "            self.chips.bet = bet\n",
    "            self.score_label.config(text=f\"Chips: {self.chips.total}\")\n",
    "            self.start_game()\n",
    "        except ValueError as e:\n",
    "            messagebox.showerror(\"Invalid Bet\", str(e) or \"Please enter a valid bet amount within your chip total.\")\n",
    "\n",
    "    def start_game(self):\n",
    "        self.player_hand = Hand()\n",
    "        self.dealer_hand = Hand()\n",
    "        self.deck = Deck()\n",
    "        self.deck.shuffle()\n",
    "        for _ in range(2):\n",
    "            self.player_hand.add_card(self.deck.deal_one())\n",
    "            self.dealer_hand.add_card(self.deck.deal_one())\n",
    "        self.update_labels()\n",
    "        self.hit_button.config(state=tk.NORMAL)\n",
    "        self.stand_button.config(state=tk.NORMAL)\n",
    "        self.bet_button.config(state=tk.DISABLED)\n",
    "\n",
    "    def display_cards(self, canvas, cards, reveal_all=True):\n",
    "        canvas.delete(\"all\")\n",
    "        for idx, card in enumerate(cards):\n",
    "            x = 50 + idx * 120\n",
    "            y = 100\n",
    "            if reveal_all or idx != 0:  # Hide the first card for the dealer if not revealed\n",
    "                canvas.create_image(x, y, image=card.image, anchor=tk.CENTER)\n",
    "            else:\n",
    "                canvas.create_image(x, y, image=self.back_of_card_image, anchor=tk.CENTER)\n",
    "\n",
    "    def update_labels(self, reveal_dealer=False):\n",
    "        self.display_cards(self.player_canvas, self.player_hand.cards, reveal_all=True)\n",
    "        self.display_cards(self.dealer_canvas, self.dealer_hand.cards, reveal_all=reveal_dealer)\n",
    "\n",
    "        self.player_label.config(text=f\"Player's Hand: {self.player_hand} (Total Value: {self.player_hand.value})\")\n",
    "        if reveal_dealer:\n",
    "            self.dealer_label.config(text=f\"Dealer's Hand: {self.dealer_hand} (Total Value: {self.dealer_hand.value})\")\n",
    "        else:\n",
    "            dealer_cards = [\"Hidden\"] + [str(self.dealer_hand.cards[1]) if len(self.dealer_hand.cards) > 1 else \"Hidden\"]\n",
    "            self.dealer_label.config(text=f\"Dealer's Hand: {', '.join(dealer_cards)}\")\n",
    "\n",
    "    def hit(self):\n",
    "        self.player_hand.add_card(self.deck.deal_one())\n",
    "        self.update_labels()\n",
    "        if self.player_hand.value > 21:\n",
    "            self.end_round(player_bust=True)\n",
    "\n",
    "    def stand(self):\n",
    "        self.player_turn = False\n",
    "        while self.dealer_hand.value < 17:\n",
    "            self.dealer_hand.add_card(self.deck.deal_one())\n",
    "        self.end_round()\n",
    "\n",
    "    def end_round(self, player_bust=False):\n",
    "        self.hit_button.config(state=tk.DISABLED)\n",
    "        self.stand_button.config(state=tk.DISABLED)\n",
    "        self.update_labels(reveal_dealer=True)\n",
    "        if player_bust:\n",
    "            messagebox.showinfo(\"Bust!\", \"You busted! Dealer wins.\")\n",
    "            self.chips.lose_bet()\n",
    "        elif self.dealer_hand.value > 21 or self.player_hand.value > self.dealer_hand.value:\n",
    "            messagebox.showinfo(\"Win!\", \"You win!\")\n",
    "            self.chips.win_bet()\n",
    "        elif self.player_hand.value < self.dealer_hand.value:\n",
    "            messagebox.showinfo(\"Lose!\", \"Dealer wins.\")\n",
    "            self.chips.lose_bet()\n",
    "        else:\n",
    "            messagebox.showinfo(\"Push\", \"It's a tie!\")\n",
    "        self.score_label.config(text=f\"Chips: {self.chips.total}\")\n",
    "        if self.chips.total <= 0:\n",
    "            messagebox.showinfo(\"Game Over\", \"You are out of chips! Restart to play again.\")\n",
    "            self.restart_game()\n",
    "        else:\n",
    "            self.next_round_button.config(state=tk.NORMAL)\n",
    "\n",
    "    def restart_game(self):\n",
    "        self.player_hand = Hand()\n",
    "        self.dealer_hand = Hand()\n",
    "        self.chips = Chips()\n",
    "        self.update_labels()\n",
    "        self.score_label.config(text=f\"Chips: {self.chips.total}\")\n",
    "        self.bet_button.config(state=tk.NORMAL)\n",
    "        self.hit_button.config(state=tk.DISABLED)\n",
    "        self.stand_button.config(state=tk.DISABLED)\n",
    "        self.next_round_button.config(state=tk.DISABLED)\n",
    "        self.player_label.config(text=\"Player's Hand: []\")\n",
    "        self.dealer_label.config(text=\"Dealer's Hand: []\")\n",
    "        self.bet_entry.delete(0, tk.END)\n",
    "\n",
    "    def next_round(self):\n",
    "        self.player_hand = Hand()\n",
    "        self.dealer_hand = Hand()\n",
    "        self.deck = Deck()\n",
    "        self.deck.shuffle()\n",
    "        self.update_labels()\n",
    "        self.bet_button.config(state=tk.NORMAL)\n",
    "        self.hit_button.config(state=tk.DISABLED)\n",
    "        self.stand_button.config(state=tk.DISABLED)\n",
    "        self.next_round_button.config(state=tk.DISABLED)\n",
    "        self.bet_entry.delete(0, tk.END)\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    root = tk.Tk()\n",
    "    game = BlackjackGame(root)\n",
    "    root.mainloop()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "252b96aa-a415-4fa0-b54e-667221ad7a91",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
